/**
 * Storyboard thumbnails — stills generated by `npm run thumbs` into
 * public/thumbs/, one per manifest scene, served statically by Vite.
 *
 * They are a build artifact, not source: the board falls back to a colored
 * placeholder card for any scene that has not been rendered yet, so a fresh
 * checkout shows a usable (if grey) storyboard before the sweep has run.
 */
import { compositionId } from '../scenes/manifest'

export const thumbUrl = (key: string): string => `/thumbs/${compositionId(key)}.jpg`
