/**
 * Act B — the roadside tree, and the two of them under it.
 *
 * This is the only shot in the act where the camera is in front of them and
 * nothing is moving, so both halves of it have to hold up close.
 *
 * ── The tree ─────────────────────────────────────────────────────────
 * The first version was Act 3.1's persimmon at 36×: a straight cylinder and
 * three spheres. That is fine at the size 3.1 uses it — twenty units tall,
 * forty metres away — and it is a broom handle when it fills the frame. So
 * this one is built properly: a leaning trunk that TAPERS (three.js's
 * TubeGeometry has one radius, so the tube is generated by hand), a root
 * flare, seven branches that fork, and foliage in clumps at the tips rather
 * than one ball on a stick.
 *
 * ── The pose ─────────────────────────────────────────────────────────
 * `pose="seated"` could not do this. Its floor-sit keeps the hips at
 * P.HIP_Y — 0.93, i.e. standing height — so the figure sits in mid-air with
 * its legs stuck out in front, which is exactly what "their butt isn't on
 * the ground" describes. And the head is a sphere at a fixed offset with no
 * neck, so `headForwardTilt` slides it back and forth without ever making
 * it look UP.
 *
 * `GoldFigure` takes a `skeleton` builder for cases like this, so the pose
 * here is authored from scratch: hips on the ground, knees drawn up, spine
 * raked BACK against the trunk, hands planted behind, and the head carried
 * well behind the shoulder line — which is what reading "looking up" is,
 * since there is no neck to angle.
 */
import { useMemo, useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { seededRandom } from '../../utils/svgHelpers'
import { GoldFigure, v, type Proportions } from '../characters/goldFigure'
import { PARENT_HAT } from './valley'
import { worldTime } from './time'
import { ramp, VALLEY_Y, TREE_X, TREE_Z, T_TREE, TREE_TRIM, PAIR_YAW } from './flight'

/* ══ Geometry helpers ═══════════════════════════════════════════════ */

/**
 * A tube swept along a Catmull-Rom curve whose radius tapers from r0 to r1.
 * three's TubeGeometry cannot do this and a trunk that does not taper reads
 * as plumbing.
 */
function taperedTube(
  pts: THREE.Vector3[], r0: number, r1: number,
  seg = 18, radial = 9, taperPow = 1.4,
): THREE.BufferGeometry {
  const curve = new THREE.CatmullRomCurve3(pts, false, 'catmullrom', 0.5)
  const frames = curve.computeFrenetFrames(seg, false)
  const pos: number[] = []
  const idx: number[] = []
  const p = new THREE.Vector3()
  for (let i = 0; i <= seg; i++) {
    const u = i / seg
    const r = r0 + (r1 - r0) * Math.pow(u, taperPow)
    curve.getPointAt(u, p)
    const N = frames.normals[i]
    const B = frames.binormals[i]
    for (let j = 0; j < radial; j++) {
      const a = (j / radial) * Math.PI * 2
      // A little lobing so the trunk is not a perfect circle in section.
      const rr = r * (1 + 0.09 * Math.sin(a * 3 + u * 2.1))
      pos.push(
        p.x + (N.x * Math.cos(a) + B.x * Math.sin(a)) * rr,
        p.y + (N.y * Math.cos(a) + B.y * Math.sin(a)) * rr,
        p.z + (N.z * Math.cos(a) + B.z * Math.sin(a)) * rr,
      )
    }
  }
  for (let i = 0; i < seg; i++) {
    for (let j = 0; j < radial; j++) {
      const a = i * radial + j
      const b = i * radial + ((j + 1) % radial)
      const c = a + radial
      const d = b + radial
      idx.push(a, c, b, b, c, d)
    }
  }
  const g = new THREE.BufferGeometry()
  g.setAttribute('position', new THREE.Float32BufferAttribute(pos, 3))
  g.setIndex(idx)
  g.computeVertexNormals()
  return g
}

type Branch = { pts: THREE.Vector3[]; r0: number; r1: number; tip: THREE.Vector3 }

/** Trunk + branches, grown from a seed. Units: the tree is ~86 tall. */
function growTree(seed: number) {
  const rand = seededRandom(seed)
  const H = 96
  const branches: Branch[] = []

  // Trunk: leans a little and kinks twice, because a straight one reads as
  // a pole however good the taper is.
  const trunk = [
    v(0, 0, 0),
    v(1.2, H * 0.16, 0.9),
    v(2.4, H * 0.36, 0.4),
    v(1.1, H * 0.58, -1.4),
    v(2.0, H * 0.78, -1.0),
  ]
  // Redwood gauge. At 5.6 it was a garden tree; this is a trunk two people
  // can lean against with room to spare. The limbs stay high and the clumps
  // stay wide, so it frames the sky rather than roofing it.
  branches.push({ pts: trunk, r0: 10.5, r1: 3.4, tip: trunk[trunk.length - 1] })

  // Primary limbs off the upper half, spiralling around the trunk.
  const N = 7
  for (let i = 0; i < N; i++) {
    const a = (i / N) * Math.PI * 2 + rand() * 0.7
    const up = 0.36 + (i / N) * 0.5 + rand() * 0.10
    const base = new THREE.Vector3(
      1.2 + up * 1.2, H * up, 0.6 - up * 2.2,
    )
    const len = 20 + rand() * 17
    const lift = 0.55 + rand() * 0.55
    const mid = base.clone().add(new THREE.Vector3(
      Math.cos(a) * len * 0.45, len * lift * 0.55, Math.sin(a) * len * 0.45,
    ))
    const tip = base.clone().add(new THREE.Vector3(
      Math.cos(a) * len, len * lift, Math.sin(a) * len,
    ))
    branches.push({ pts: [base, mid, tip], r0: 3.0, r1: 0.8, tip })

    // One fork off most limbs.
    if (rand() > 0.25) {
      const a2 = a + (rand() - 0.5) * 1.5
      const l2 = len * (0.42 + rand() * 0.3)
      const tip2 = mid.clone().add(new THREE.Vector3(
        Math.cos(a2) * l2, l2 * (0.5 + rand() * 0.6), Math.sin(a2) * l2,
      ))
      branches.push({
        pts: [mid, mid.clone().lerp(tip2, 0.5), tip2],
        r0: 1.5, r1: 0.45, tip: tip2,
      })
    }
  }
  return { branches, H }
}

/* ══ The tree ═══════════════════════════════════════════════════════ */

export function Tree({ seed = 3301 }: { seed?: number }) {
  const { branches } = useMemo(() => growTree(seed), [seed])

  const wood = useMemo(() => new THREE.MeshStandardMaterial({
    color: '#4A3326', roughness: 0.96, metalness: 0, flatShading: false,
  }), [])
  const leafA = useMemo(() => new THREE.MeshStandardMaterial({
    color: '#24401E', roughness: 1, metalness: 0, flatShading: true,
  }), [])
  const leafB = useMemo(() => new THREE.MeshStandardMaterial({
    color: '#2F5426', roughness: 1, metalness: 0, flatShading: true,
  }), [])
  const leafC = useMemo(() => new THREE.MeshStandardMaterial({
    color: '#1A3018', roughness: 1, metalness: 0, flatShading: true,
  }), [])
  const fruit = useMemo(() => new THREE.MeshStandardMaterial({
    color: '#E4661F', roughness: 0.65, metalness: 0,
    emissive: new THREE.Color('#7A2A08'), emissiveIntensity: 0.45,
  }), [])

  const geos = useMemo(
    () => branches.map(b => taperedTube(b.pts, b.r0, b.r1, b.pts.length > 3 ? 22 : 12)),
    [branches],
  )

  /** Root flare: a squashed cone so the trunk grows OUT of the ground
   *  rather than being pushed into it. */
  const flare = useMemo(() => {
    const g = new THREE.ConeGeometry(19, 16, 10, 1, true)
    g.translate(0, 8, 0)
    g.scale(1, -1, 1)
    g.translate(0, 8, 0)
    return g
  }, [])

  const clumps = useMemo(() => {
    const rand = seededRandom(seed + 17)
    const out: { p: THREE.Vector3; r: number; m: number }[] = []
    branches.forEach((b, i) => {
      if (i === 0) return
      const n = 3 + Math.floor(rand() * 3)
      for (let k = 0; k < n; k++) {
        const along = 0.55 + rand() * 0.55
        const base = b.pts[0].clone().lerp(b.tip, Math.min(1.05, along))
        out.push({
          p: base.add(new THREE.Vector3(
            (rand() - 0.5) * 14, (rand() - 0.2) * 11, (rand() - 0.5) * 14,
          )),
          r: 7 + rand() * 8,
          m: Math.floor(rand() * 3),
        })
      }
    })
    return out
  }, [branches, seed])

  const fruits = useMemo(() => {
    const rand = seededRandom(seed + 41)
    return clumps.filter(() => rand() > 0.68).map(c => ({
      p: c.p.clone().add(new THREE.Vector3(
        (rand() - 0.5) * c.r, -c.r * (0.5 + rand() * 0.5), (rand() - 0.5) * c.r,
      )),
    }))
  }, [clumps, seed])

  return (
    <group>
      <mesh geometry={flare} material={wood} />
      {geos.map((g, i) => <mesh key={i} geometry={g} material={wood} />)}
      {clumps.map((c, i) => (
        <mesh key={i} position={c.p} material={c.m === 0 ? leafA : c.m === 1 ? leafB : leafC}
          rotation={[i * 0.7, i * 1.3, i * 0.4]}>
          <icosahedronGeometry args={[c.r, 0]} />
        </mesh>
      ))}
      {fruits.map((f, i) => (
        <mesh key={i} position={f.p} material={fruit}>
          <sphereGeometry args={[1.5, 8, 8]} />
        </mesh>
      ))}
    </group>
  )
}

/* ══ The pose ═══════════════════════════════════════════════════════ */

/**
 * Sitting on the ground with the back against the trunk, propped on both
 * hands, head tipped right back. Authored in the figure's own proportions so
 * the adult and the child sit the same way.
 */
function restingSkeleton({ P }: { P: Proportions }) {
  const R = P.R
  /**
   * Every joint is a real joint and every segment is a real length. The
   * first pass hand-authored both, so the arms started 0.10 out from the
   * shoulder and the legs 0.07 out from the hip — a gap the sphere caps
   * could not cover, which is what "their arms and torso aren't attached"
   * is. Limbs now START at the joint they hang from, and thigh/shin/upper
   * arm/forearm come off `Proportions` so the adult and the child are the
   * same person at two sizes.
   */
  const legLen = P.HIP_Y - P.FOOT_Y
  const armLen = (P.SHOULDER_Y - P.HIP_Y) * 1.02
  const torso = P.SHOULDER_Y - P.HIP_Y
  const neck = P.HEAD_Y - P.SHOULDER_Y

  /**
   * They start looking DOWN at the ground in front of them and then, over
   * about two seconds, both tip their heads back together. `up` is that
   * move, and it drives the head AND the rake of the spine — a head tipping
   * back on a rigid torso reads as a broken neck; the whole upper body has
   * to go with it.
   */
  const up = ramp(worldTime(), T_TREE + 4.4 - TREE_TRIM, T_TREE + 6.4 - TREE_TRIM)

  const hip = v(0, R + legLen * 0.06, 0)
  const shoulder = v(0, hip.y + torso * (0.92 - up * 0.03), -torso * (0.30 + up * 0.20))
  // Start LEVEL, not chin-on-chest: they are looking out across the fields,
  // not at their own knees. The travel is the last third of what it was.
  const head = v(
    0,
    shoulder.y + neck * (0.84 + up * 0.10),
    shoulder.z + neck * (0.12 - up * 0.92),
  )

  const spine = [
    hip,
    v(0, hip.y + torso * 0.30, -torso * 0.10),
    v(0, hip.y + torso * 0.60, -torso * 0.27),
    shoulder,
  ]

  /** Knee drawn up and out, heel on the ground in front. */
  const leg = (s: number) => {
    const knee = v(
      hip.x + s * legLen * 0.17,
      hip.y + legLen * 0.46,
      hip.z + legLen * 0.34,
    )
    const heel = v(
      knee.x + s * legLen * 0.06,
      R,
      knee.z + legLen * 0.44,
    )
    return [hip, hip.clone().lerp(knee, 0.5), knee, knee.clone().lerp(heel, 0.5), heel]
  }

  /** Propped on both hands, planted behind the hips. */
  const arm = (s: number) => {
    const elbow = v(
      shoulder.x + s * armLen * 0.34,
      shoulder.y - armLen * 0.46,
      shoulder.z - armLen * 0.22,
    )
    const hand = v(
      elbow.x + s * armLen * 0.16,
      R,
      elbow.z - armLen * 0.16,
    )
    return [shoulder, shoulder.clone().lerp(elbow, 0.5), elbow, elbow.clone().lerp(hand, 0.5), hand]
  }

  /** A NECK. The rig hangs the head off the spine as a free sphere, which
   *  is fine on a walking figure whose head sits directly over its
   *  shoulders and obviously wrong the moment the head is carried back to
   *  look up — it floats. This is the segment that was missing. */
  const neckCurve = [
    shoulder,
    shoulder.clone().lerp(head, 0.45),
    head.clone().lerp(shoulder, 0.22),
  ]

  return {
    curves: [
      { points: spine, radius: R, segments: 14 },
      { points: neckCurve, radius: R * 0.82, segments: 8 },
      { points: arm(-1), radius: R * 0.88, segments: 14 },
      { points: arm(+1), radius: R * 0.88, segments: 14 },
      { points: leg(-1), radius: R, segments: 14 },
      { points: leg(+1), radius: R, segments: 14 },
    ],
    spheres: [{ center: head, radius: P.RH }],
  }
}

/** Other people, further along the verge. Same pose, same rig, smaller and
 *  dimmer with distance. */
const OTHERS = [
  { x: 250, z: -2340, ry: -0.72, s: 0.92, gap: 17 },
  { x: 372, z: -2760, ry: -1.34, s: 0.86, gap: -16 },
  { x: 214, z: -2880, ry: -0.94, s: 0.80, gap: 15 },
]

/* ══ The scene ══════════════════════════════════════════════════════ */

export function RoadsideTree() {
  const lamp = useRef<THREE.PointLight>(null)
  const rim = useRef<THREE.PointLight>(null)
  useFrame(() => {
    const on = ramp(worldTime(), T_TREE - 0.2, T_TREE + 0.6)
    // Their own glow on the trunk and the grass is the only reason anything
    // in this shot is lit at all.
    if (lamp.current) lamp.current.intensity = 2600 * on
    if (rim.current) rim.current.intensity = 900 * on
  })

  return (
    <group position={[TREE_X, VALLEY_Y + 4, TREE_Z]}>
      <group rotation={[0, 1.9, 0]}>
        <Tree />
      </group>
      {/* Grass at the foot of it, so they are sitting on something. */}
      <mesh position={[-10, 0.6, 4]} rotation={[-Math.PI / 2, 0, 0]}>
        <circleGeometry args={[54, 20]} />
        <meshStandardMaterial color="#2C3A22" roughness={1} />
      </mesh>
      {/* Facing the lens, backs to the trunk, separated ACROSS the frame
          rather than along the view axis — both derived from the camera
          bearing, not guessed. rotation.y = atan2 of the bearing to the
          lens, so local +z points at the camera and local x runs across the
          shot; in profile a floor-sit is a tangle of sticks, and separated
          along the axis the child disappears behind the parent. */}
      {/* BOTH against the trunk. They were 32 units apart with the tree
          between them; a redwood is wide enough that two people share one
          side of it, which is the whole point of the shot. */}
      <group position={[-22, 1, 2]} rotation={[0, PAIR_YAW, 0]}>
        {/* The pair keep the two temperatures they have on the road — the
            parent the deeper gold, the child the cooler, brighter one — and
            the parent keeps the hat, shoved right back off the brow, because
            nobody looks straight up at the sky through a brim. */}
        <group position={[-9, 0, 0]} scale={20}>
          <GoldFigure material="goldParent" glow={1.0} skeleton={restingSkeleton}
            hat={PARENT_HAT} hatTilt={-1.05} />
        </group>
        <group position={[9, 0, 2]} scale={13.6}>
          <GoldFigure kind="child" material="goldChild" glow={1.4} skeleton={restingSkeleton} />
        </group>
      </group>
      {/* And they are not the only ones out here. Three more groups down the
          verge doing exactly the same thing — the valley is full of people
          who have stopped to look up. */}
      {OTHERS.map((o, i) => (
        <group key={i} position={[o.x, 1, o.z]} rotation={[0, o.ry, 0]}>
          <group scale={20 * o.s}>
            <GoldFigure material="goldAmber" glow={0.8} skeleton={restingSkeleton} />
          </group>
          <group position={[o.gap, 0, 2]} scale={13.6 * o.s}>
            <GoldFigure kind="child" material="goldAmber" glow={1.05} skeleton={restingSkeleton} />
          </group>
        </group>
      ))}
      <pointLight ref={lamp} position={[-26, 20, 14]} color="#FFC24E"
        intensity={0} distance={240} decay={1.9} />
      {/* A cold touch from the sky side, so the trunk has two sides to it. */}
      <pointLight ref={rim} position={[30, 90, -40]} color="#8FA8E0"
        intensity={0} distance={420} decay={1.7} />
    </group>
  )
}
