#!/usr/bin/env node
/**
 * new-shot.mjs — scaffold a scene so "add a shot" is one command.
 *
 *   node scripts/new-shot.mjs --key story.7 --title "The Return" \
 *       --template world --world LANTERN_VALLEY --lighting night \
 *       --group Studio --duration 10 [--register]
 *
 * Templates:
 *   world  — shot inside an existing world (WorldMount + camera move)
 *   three  — blank createScene 3D scene (camera move + demo mesh)
 *   dom    — DOM/SVG scene reading useAnimTime()
 *
 * Writes src/scenes/generated/<Name>.tsx (or --dir), prints the
 * regex-safe manifest line; --register inserts it into
 * src/scenes/manifest.ts before the closing of SCENES (append-to-group
 * ordering is left to the author). The generated file compiles as-is.
 */
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs'
import path from 'node:path'
import { fileURLToPath } from 'node:url'

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..')
const args = process.argv.slice(2)
const flag = (name, dflt) => {
  const i = args.indexOf(`--${name}`)
  return i !== -1 && args[i + 1] && !args[i + 1].startsWith('--') ? args[i + 1] : dflt
}

const key = flag('key')
const title = flag('title', 'Untitled Shot')
const template = flag('template', 'world')
const group = flag('group', 'Studio')
const duration = parseFloat(flag('duration', '10'))
const world = flag('world', 'LANTERN_VALLEY')
const lighting = flag('lighting', 'night')
const dir = flag('dir', 'src/scenes/generated')
const register = args.includes('--register')

if (!key) {
  console.error('usage: node scripts/new-shot.mjs --key <scene.key> --title "..." [--template world|three|dom] [--world LANTERN_VALLEY] [--lighting night] [--group Studio] [--duration 10] [--dir src/...] [--register]')
  process.exit(1)
}

const compName = key.replace(/[^a-zA-Z0-9]+(.)?/g, (_, c) => (c ? c.toUpperCase() : ''))
  .replace(/^./, c => c.toUpperCase())
const fileBase = `Shot_${compName}`
const outDir = path.join(root, dir)
const outFile = path.join(outDir, `${fileBase}.tsx`)
if (existsSync(outFile)) {
  console.error(`refusing to overwrite ${outFile}`)
  process.exit(1)
}

// Depth of the scene file below src/ decides the ../ prefix.
const up = path.relative(path.dirname(outFile), path.join(root, 'src')).split(path.sep).map(() => '..').join('/')
  .replace(/\.\.\/?$/, '..') || '..'
const rel = (p) => `${path.relative(path.dirname(outFile), path.join(root, 'src', p)).split(path.sep).join('/')}`

const TEMPLATES = {
  world: `/**
 * ${key} — ${title} (${lighting}, in the ${world} world).
 * Generated by scripts/new-shot.mjs — edit freely.
 */
import { createScene } from '${rel('scenes/createScene')}'
import { WorldMount } from '${rel('studio/worlds/World')}'
import { ${world} } from '${rel('studio/worlds/LanternValley')}'

export default createScene({
  background: '#080E1F',
  three: {
    camera: { position: [12, 5, 12], fov: 44 },
    debugTarget: [0, 1.5, 0],
  },
  cameraMoves: [{
    a: { pos: [12, 5, 12], target: [0, 1.5, 0] },
    b: { pos: [8, 3.5, 8], target: [0, 1.8, -2] },
    t0: 0.4, t1: ${Math.max(1, duration - 0.4)}, ease: 'inout',
  }],
}, function ${compName}() {
  return (
    <WorldMount
      world={${world}}
      shot={{ lighting: '${lighting}' }}
    />
  )
})
`,
  three: `/**
 * ${key} — ${title}. Generated by scripts/new-shot.mjs — edit freely.
 */
import { useRef } from 'react'
import { useFrame } from '@react-three/fiber'
import * as THREE from 'three'
import { getAnimTime } from '${rel('hooks/useAnimTime')}'
import { createScene } from '${rel('scenes/createScene')}'

function Pulse() {
  const ref = useRef<THREE.Mesh>(null)
  useFrame(() => {
    if (ref.current) ref.current.position.y = 1 + Math.sin(getAnimTime() * 2) * 0.4
  })
  return <mesh ref={ref}><boxGeometry /><meshStandardMaterial color="#D4A843" /></mesh>
}

export default createScene({
  background: '#0A1628',
  three: { camera: { position: [0, 2, 8], fov: 45 }, debugTarget: [0, 1, 0] },
}, function ${compName}() {
  return (<><ambientLight intensity={0.4} /><directionalLight position={[3, 5, 2]} /><Pulse /></>)
})
`,
  dom: `/**
 * ${key} — ${title}. Generated by scripts/new-shot.mjs — edit freely.
 */
import { useAnimTime } from '${rel('hooks/useAnimTime')}'

export default function ${compName}() {
  const t = useAnimTime()
  return (
    <div style={{
      position: 'fixed', inset: 0, background: '#0A1628', color: '#E8D5B5',
      display: 'flex', alignItems: 'center', justifyContent: 'center',
      fontFamily: 'system-ui, sans-serif', fontSize: 32,
      opacity: Math.min(1, t / 2),
    }}>
      ${title}
    </div>
  )
}
`,
}

const src = TEMPLATES[template]
if (!src) {
  console.error(`unknown template '${template}' — one of: ${Object.keys(TEMPLATES).join(', ')}`)
  process.exit(1)
}
void up

mkdirSync(outDir, { recursive: true })
writeFileSync(outFile, src)

const manifestPath = path.join(root, 'src/scenes/manifest.ts')
const importPath = path.relative(path.join(root, 'src/scenes'), outFile).split(path.sep).join('/').replace(/\.tsx$/, '')
const importSpec = importPath.startsWith('.') ? importPath : `./${importPath}`
const line = `  { key: '${key}', title: '${title.replace(/'/g, "\\'")}', group: '${group}', durationSec: ${duration}, load: () => import('${importSpec}') },`

console.log(`wrote ${path.relative(root, outFile)}`)
if (register) {
  const manifest = readFileSync(manifestPath, 'utf8')
  if (manifest.includes(`key: '${key}'`)) {
    console.error(`manifest already has key '${key}' — line NOT inserted`)
  } else {
    // Insert as the last entry of SCENES (before its closing "\n]").
    const m = manifest.match(/const SCENES[^=]*=\s*\[[\s\S]*?\n\]/)
    if (!m) throw new Error('cannot locate SCENES array')
    const updated = manifest.replace(m[0], m[0].replace(/\n\]$/, `\n${line}\n]`))
    writeFileSync(manifestPath, updated)
    console.log(`registered '${key}' in src/scenes/manifest.ts`)
  }
} else {
  console.log('add to src/scenes/manifest.ts (SCENES):')
  console.log(line)
}
